import Head from "next/head";
import Link from "next/link";
import { PrismaClient } from "@prisma/client";
import Layout from "@/components/Layout";

const prisma = new PrismaClient();

export default function Movie({ movie }) {
  return (
    <>
      <Head>
        <title>
          {movie.title} ({movie.year})
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="px-6 py-8 space-y-6 bg-gray-200 rounded-md sm:grid sm:grid-cols-2 sm:gap-x-6 sm:gap-y-10 sm:space-y-0 lg:gap-x-8">
          <div
            style={{
              position: "relative",
              height: "400px",
              width: "270px",
            }}
            className="m-auto bg-gray-300 rounded-md"
          >
            <img
              src={movie.imageUrl || "/defaultMovie.png"}
              alt={movie.title}
              className="h-full rounded-md "
              title={movie.title}
              width="270"
              height="400"
            />
          </div>

          <div className="flex items-center">
            <div>
              <h1 className="text-3xl font-bold text-gray-800 md:text-4xl">
                {movie.title}
              </h1>
              <p className="mt-2 text-gray-600">{movie.year}</p>

              <p className="max-w-md mt-4 leading-relaxed text-gray-700">
                {movie.description}
              </p>

              <div className="mt-4">
                <Link href="/">
                  <a className="text-blue-700 underline hover:text-blue-800">
                    ← Back to home
                  </a>
                </Link>
              </div>
            </div>
          </div>
        </div>
      </Layout>
      ;
    </>
  );
}

export async function getServerSideProps(context) {
  const { slug } = context.query;

  const movie = await prisma.movie.findFirst({
    where: {
      slug: slug,
    },
  });

  return {
    props: {
      movie,
    },
  };
}
